# Use higher power BT for better connection/latency
# CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Sleep/Idle
# CONFIG_ZMK_SLEEP=y
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# Eager debounce for presses. Increase if you have issues with double-presses.
# CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=15
# CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=15
